### PR TITLE
Translation to turkish version your project

### PR DESCRIPTION
**Pull request by lasasur**
I translated 1025 words at the answers-by-questions.json file.

This is turkish translated file in Crowdin  : https://crowdin.com/translate/dollar-street/39321/en-tr

My user activity; https://crowdin.com/project/dollar-street/activity_stream

Merge this my pull request and I can continue this translation.

### CODE REVIEW

**Comment by Miffael** [comment]
Upotian from today support Crowdin https://steemit.com/utopian-io/@utopian-io/utopian-rules-update-9-crowdin-support-and-moderation-quiz-quality-over-quantity

We don't have translations in this project, please create request in our Crowdin project https://crowdin.com/project/dollar-street

**Comment by lasasur** [comment]
But now Utopian doesn't accept crowdin translation. Utopian said '' You must create translate request in GitHub and your request must be merged.'' It 's a new rule. What should I do ?

This is new rule ''Translations must be provided as a Pull Requst on the GitHub repository.''

Please help :(

**Comment by Miffael** [comment]
As a contributor you can start contributing again on CrowdIn as long as you are enabled as a proofreader on the project. In order to get enabled as a proofreader, you should get in touch with the CrowdIn project owner or managers.

By enabling you as a proofreader the project owner entrust you will be able to successfully submit quality translations. Utopian relies on this simple fact to judge/predict wether your contribution will be valid or not.

You can contact our manager there https://crowdin.com/profile/hishamnajam

**Comment by lasasur** [comment]
Thanks for informatin. I created contact your manager in crowdin. I hope he will reply me as soon as possible.

**Pull request closed without merging**
